// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single ACP content block inside a `session/update` agentMessage update.
 */
export type AcpContentBlock = { "type": "text", text: string, };
