// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcpPermissionOptionKind } from "./AcpPermissionOptionKind";

/**
 * Outcome chosen by the client in response to a `session/request_permission`.
 */
export type AcpPermissionOutcome = { "type": "option", kind: AcpPermissionOptionKind, };
