// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome kinds offered in `session/request_permission`.
 */
export type AcpPermissionOptionKind = "allow_once" | "allow_always" | "reject_once" | "reject_always";
