// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcpPermissionOptionKind } from "./AcpPermissionOptionKind";

/**
 * A single permission option presented to the client.
 */
export type AcpPermissionOption = { label: string, kind: AcpPermissionOptionKind, };
