// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcpPermissionOption } from "./AcpPermissionOption";
import type { AcpToolCall } from "./AcpToolCall";

/**
 * Params for the ACP `session/request_permission` server→client request.
 */
export type AcpRequestPermissionParams = { sessionId: string, toolCall: AcpToolCall, options: Array<AcpPermissionOption>, };
