// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Params for the ACP `session/new` method.
 * ACP only requires `cwd` and `mcpServers`; all codex-specific fields are
 * supplied by server defaults or ignored until later gaps are addressed.
 */
export type AcpSessionNewParams = { cwd: string, mcpServers: Array<JsonValue>, };
