// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of a single session returned by `session/list`.
 */
export type AcpSessionInfo = { sessionId: string, cwd: string | null, };
