// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for ACP `terminal/kill` (server→client): sends SIGKILL to the
 * terminal process.
 */
export type AcpTerminalKillParams = { terminalId: string, };
