// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for ACP `terminal/release` (server→client): releases the terminal
 * handle without killing the process.
 */
export type AcpTerminalReleaseParams = { terminalId: string, };
