// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A tool call reference inside `session/request_permission`.
 */
export type AcpToolCall = { id: string, name: string, input: JsonValue, };
