// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for ACP `terminal/output` (server→client): writes data to the
 * terminal's stdin.
 */
export type AcpTerminalOutputParams = { terminalId: string, 
/**
 * Base64-encoded bytes to write to the terminal's stdin.
 */
data: string, };
