// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for ACP `terminal/create` (server→client): asks the client to open
 * a new terminal process and return a handle.
 */
export type AcpTerminalCreateParams = { sessionId: string, };
