// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for ACP `terminal/waitForExit` (server→client): blocks until the
 * process exits and returns the exit code.
 */
export type AcpTerminalWaitForExitParams = { terminalId: string, };
