// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpCapabilities } from "./McpCapabilities";
import type { PromptCapabilities } from "./PromptCapabilities";

export type AgentCapabilities = { 
/**
 * Server supports `session/load` (resume with history replay).
 */
loadSession: boolean, 
/**
 * Server supports `session/close`.
 */
closeSession: boolean, 
/**
 * Server supports `session/list`.
 */
listSessions: boolean, 
/**
 * Server supports `session/resume` (resume without history replay).
 */
resumeSession: boolean, 
/**
 * Server supports `authenticate`.
 */
authenticate: boolean, promptCapabilities: PromptCapabilities | null, mcpCapabilities: McpCapabilities | null, };
