// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentCapabilities } from "./AgentCapabilities";
import type { AgentInfo } from "./AgentInfo";
import type { JsonValue } from "./serde_json/JsonValue";

export type InitializeResponse = { userAgent: string, 
/**
 * ACP protocol version negotiated with the client (e.g. `"2025-05-12"`).
 */
protocolVersion: string, agentCapabilities: AgentCapabilities | null, agentInfo: AgentInfo | null, 
/**
 * Auth methods supported by the server (empty = no auth required).
 */
authMethods: Array<JsonValue> | null, };
