// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientInfo } from "./ClientInfo";
import type { InitializeCapabilities } from "./InitializeCapabilities";

export type InitializeParams = { 
/**
 * ACP protocol version the client wishes to use (e.g. `"2025-05-12"`).
 */
protocolVersion: string | null, clientInfo: ClientInfo | null, clientCapabilities: InitializeCapabilities | null, };
