// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientInfo } from "./ClientInfo";
import type { InitializeCapabilities } from "./InitializeCapabilities";
import type { JsonValue } from "./serde_json/JsonValue";

export type InitializeParams = { 
/**
 * ACP protocol version the client wishes to use. Stored as raw JSON so
 * we can echo back the exact type (integer or string) the client sent.
 */
protocolVersion: JsonValue | null, clientInfo: ClientInfo | null, clientCapabilities: InitializeCapabilities | null, };
