// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A JSON-RPC request identifier — either a string or an integer.
 *
 * `#[serde(untagged)]` is intentionally NOT used here. Untagged enum
 * deserialization inside serde's internally-tagged `ClientRequest` enum
 * (which uses `#[serde(tag = "method")]`) triggers a known serde limitation:
 * the error from the first failed variant attempt ("invalid type: integer,
 * expected a string") leaks out instead of being silently retried. A manual
 * `Visitor` with `deserialize_any` avoids this.
 */
export type RequestId = string | number;
