// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcpRequestPermissionParams } from "./AcpRequestPermissionParams";
import type { AcpTerminalCreateParams } from "./AcpTerminalCreateParams";
import type { AcpTerminalKillParams } from "./AcpTerminalKillParams";
import type { AcpTerminalOutputParams } from "./AcpTerminalOutputParams";
import type { AcpTerminalReleaseParams } from "./AcpTerminalReleaseParams";
import type { AcpTerminalWaitForExitParams } from "./AcpTerminalWaitForExitParams";
import type { ApplyPatchApprovalParams } from "./ApplyPatchApprovalParams";
import type { ExecCommandApprovalParams } from "./ExecCommandApprovalParams";
import type { RequestId } from "./RequestId";
import type { CommandExecutionRequestApprovalParams } from "./v2/CommandExecutionRequestApprovalParams";
import type { DynamicToolCallParams } from "./v2/DynamicToolCallParams";
import type { FileChangeRequestApprovalParams } from "./v2/FileChangeRequestApprovalParams";
import type { ToolRequestUserInputParams } from "./v2/ToolRequestUserInputParams";

/**
 * Request initiated from the server and sent to the client.
 */
export type ServerRequest = { "method": "item/commandExecution/requestApproval", id: RequestId, params: CommandExecutionRequestApprovalParams, } | { "method": "item/fileChange/requestApproval", id: RequestId, params: FileChangeRequestApprovalParams, } | { "method": "item/tool/requestUserInput", id: RequestId, params: ToolRequestUserInputParams, } | { "method": "item/tool/call", id: RequestId, params: DynamicToolCallParams, } | { "method": "session/request_permission", id: RequestId, params: AcpRequestPermissionParams, } | { "method": "terminal/create", id: RequestId, params: AcpTerminalCreateParams, } | { "method": "terminal/output", id: RequestId, params: AcpTerminalOutputParams, } | { "method": "terminal/kill", id: RequestId, params: AcpTerminalKillParams, } | { "method": "terminal/waitForExit", id: RequestId, params: AcpTerminalWaitForExitParams, } | { "method": "terminal/release", id: RequestId, params: AcpTerminalReleaseParams, } | { "method": "applyPatchApproval", id: RequestId, params: ApplyPatchApprovalParams, } | { "method": "execCommandApproval", id: RequestId, params: ExecCommandApprovalParams, };
