// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcpContentBlock } from "./AcpContentBlock";

/**
 * Tagged payload for the ACP `session/update` server→client notification.
 * Matches the ACP `SessionUpdate` wire format with `"sessionUpdate"` discriminant.
 */
export type SessionUpdatePayload = { "sessionUpdate": "agent_message_chunk", content: AcpContentBlock, } | { "sessionUpdate": "error", error: string, };
