// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionPromptResource } from "./SessionPromptResource";

/**
 * A single content block inside a Zed ACP `session/prompt` message.
 */
export type SessionPromptContent = { "type": "text", text: string, } | { "type": "resource", resource: SessionPromptResource, } | { "type": "unknown" };
