// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionUpdatePayload } from "./SessionUpdatePayload";

/**
 * Params for the ACP `session/update` server→client notification.
 */
export type SessionUpdateNotification = { sessionId: string, update: SessionUpdatePayload, };
