// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for ACP `session/resume`.
 */
export type SessionResumeResponse = { sessionId: string, };
