// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for the ACP `session/new` method.
 */
export type SessionNewResponse = { sessionId: string, };
