// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An embedded resource content block in a Zed ACP prompt.
 */
export type SessionPromptResource = { uri: string, mimeType: string | null, text: string | null, };
