// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionPromptContent } from "./SessionPromptContent";

/**
 * Params for the Zed ACP `session/prompt` method.
 */
export type SessionPromptParams = { sessionId: string, 
/**
 * Content blocks — ACP sends an array of typed blocks.
 */
prompt: Array<SessionPromptContent>, };
