// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcpContentBlock } from "./AcpContentBlock";

/**
 * Tagged payload for the ACP `session/update` server→client notification.
 */
export type SessionUpdatePayload = { "type": "agentMessage", role: string, content: Array<AcpContentBlock>, } | { "type": "error", error: string, };
