// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for the Zed ACP `session/cancel` notification (client → server).
 */
export type SessionCancelParams = { sessionId: string, };
