// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Params for ACP `session/resume` (resume without history replay).
 */
export type SessionResumeParams = { sessionId: string, };
